module.exports = {
  ERROR_TYPES: {
    UNEXPECTED_ERROR: 'UNEXPECTED_ERROR',
    PAY_PAL_GET_PAYMENT_FAILED: 'PAY_PAL_GET_PAYMENT_FAILED',
    DRUPAL_GET_NODES_FAILED: 'DRUAPL_GET_NODES_FAILED',
    DRUPAL_UPDATE_NODES_FAILED: 'DRUPAL_UPDATE_NODES_FAILED',
    PAY_PAL_NOT_MATCHING_DRUPAL: 'PAY_PAL_NOT_MATCHING_DRUPAL',
    PURCHASED_ITEMS_NO_LONGER_AVAILABLE: 'PURCHASED_ITEMS_NO_LONGER_AVAILABLE',
    PAY_PAL_UNABLE_TO_REFUND: 'PAY_PAL_UNABLE_TO_REFUND'
  }
}
