module.exports = {
  ERROR_TYPES: {
    UNEXPECTED_ERROR: 'UNEXPECTED_ERROR',
    DRUPAL_GET_NODES_FAILED: 'DRUAPL_GET_NODES_FAILED',
    DRUPAL_UPDATE_NODES_FAILED: 'DRUPAL_UPDATE_NODES_FAILED',
    DRUPAL_PRICE_NOT_MATCHING_SENT_PRICE: 'DRUPAL_PRICE_NOT_MATCHING_SENT_PRICE',
    PURCHASED_ITEMS_NO_LONGER_AVAILABLE: 'PURCHASED_ITEMS_NO_LONGER_AVAILABLE',
    UNABLE_TO_CREATE_PAYPAL_PAYMENT: 'UNABLE_TO_CREATE_PAYPAL_PAYMENT',
  }
}
